POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email":"admin1@gmail.com",
  "password":"123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"admin@gmail.com",
  "password":"123"
}
###
GET http://localhost:5000/api/auth/users

### Product API
GET http://localhost:5000/api/products/

###
GET http://localhost:5000/api/products/64246a51588b4733b4778ee5

### Add new product
POST http://localhost:5000/api/products/
Content-Type: application/json

{
    "categoryId": "642469d5588b4733b4778edf",
    "image": ["scale-20.jpg", "scale-20-1.jpg"],
    "name": "test",
    "price": 7750000,
    "amount": 99
  }

###
PUT http://localhost:5000/api/products/64259ab3a61888100795b0af
Content-Type: application/json

{
  "image": ["order-19-1.jpg"],
  "name": "Final Fantasy VII Remake Adorable Arts Aerith Gainsborough",
  "price": 2150052,
  "amount": 89
}

###
DELETE http://localhost:5000/api/products/64259ab3a61888100795b0af


### Get all categories
GET http://localhost:5000/api/categories

###
POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "name": "MegaHouse"
}

###
PUT http://localhost:5000/api/categories/6424646ceef0f4e1ae6395a8
Content-Type: application/json

{
  "name": "Square Enix"
}

###
GET http://localhost:5000/api/categories/6424646ceef0f4e1ae6395a8

###
DELETE http://localhost:5000/api/categories/6424646ceef0f4e1ae6395a8


###
POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "userId":"642b1a295d7254ca6a19e91f",
  "productId":["64246a3e588b4733b4778ee3"],
  "paypalPayment": {
    "name":"123"
  }
}


###
GET http://localhost:5000/api/orders
###
GET http://localhost:5000/api/orders/642edd1e7c19ea73ec76bfc2

###
PUT http://localhost:5000/api/orders/642edd1e7c19ea73ec76bfc2
Content-Type: application/json

{
  "userId": "642b1a295d7254ca6a19e91f",
  "productId": [
    "64246a3e588b4733b4778ee3"
  ],
  "status": "completed",
  "paypalPayment": {
    "name": "123"
  }
}

###
DELETE http://localhost:5000/api/orders/642edd1e7c19ea73ec76bfc2